const { json } = require("express");
const flags = require("./flags.json");
const countrys = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Anguilla",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Aruba",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bermuda",
  "Bhutan",
  "Bolivia",
  "Bouvet Island",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Cape Verde",
  "Cayman Islands",
  "Central African Republic",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Costa Rica",
  "Côte d'Ivoire (Ivory Coast)",
  "Croatia",
  "Cuba",
  "Curaçao",
  "Cyprus",
  "Czechia",
  "Republic of the Congo",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "England",
  "Equatorial Guinea",
  "Estonia",
  "Eswatini (Swaziland)",
  "Ethiopia",
  "Faroe Islands",
  "Falkland Islands",
  "Fiji",
  "Finland",
  "France",
  "French Polynesia",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Gibraltar",
  "Greece",
  "Greenland",
  "Grenada",
  "Guatemala",
  "Guernsey",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Honduras",
  "Hong Kong",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Isle of Man",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jersey",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kosovo",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macau",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Montserrat",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Caledonia",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Macedonia",
  "Northern Mariana Islands",
  "Northern Ireland",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Helena, Ascension and Tristan da Cunha",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "São Tomé and Príncipe",
  "Saudi Arabia",
  "Scotland",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Sint Maarten",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Korea",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Venezuela",
  "Vietnam",
  "Wales",
  "Wallis and Futuna",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];
// let codesCont = [
//   'af', 'al', 'dz',     'ad', 'ao', 'ai',     'ag',     'ar',
//   'au', 'at', 'az',     'bs', 'bh', 'bd',     'bb',     'by',
//   'be', 'bz', 'bm',     'bo', 'br', 'bg',     'kh',     'ca',
//   'ky', 'cl', 'cn',     'co', 'cr', 'ci',     'hr',     'cy',
//   'cz', 'dk', 'dm',     'do', 'ec', 'eg',     'sv',     'gb-eng',
//   'gq', 'ee', 'fo',     'fk', 'fi', 'fr',     'de',     'gh',
//   'gi', 'gr', 'gl',     'gd', 'gt', 'gg',     'gn',     'gy',
//   'hn', 'hk', 'hu',     'is', 'in', 'id',     'ir',     'ie',
//   'im', 'il', 'it',     'jm', 'jp', 'je',     'jo',     'kz',
//   'ke', 'kw', 'la',     'lv', 'lb', 'li',     'lt',     'lu',
//   'mo', 'mw', 'my',     'mv', 'mt', 'mu',     'mx',     'md',
//   'mc', 'mn', 'me',     'ms', 'ma', 'mz',     'mm',     'np',
//   'nl', 'nz', 'ng',     'mk', 'mp', 'gb-nir', 'no',     'om',
//   'pk', 'pw', 'pa',     'py', 'pe', 'ph',     'pl',     'pt',
//   'qa', 'ro', 'ru',     'rw', 'sh', 'kn',     'lc',     'vc',
//   'sm', 'sa', 'gb-sct', 'sn', 'rs', 'sc',     'sg',     'sk',
//   'si', 'za', 'kr',     'es', 'lk', 'sr',     'se',     'ch',
//   'tw', 'th', 'tt',     'tn', 'tr', 'tc',     'ug',     'ua',
//   'ae', 'gb', 'us',     'uy', 've', 'vn',     'gb-wls', 'zw'
// ]

// Crea un array con el pais y su code ['Colombia', 'co', 'Ecuador', 'ec']
let result = [];
for (var i in flags) {
  result.push(i, flags[i]);
}
let resultCont = [];
let resultCode = [];
//separa cada pais y su code ['Ecuador'] ['ec']
for (var k in result) {
  if (k % 2 === 0) {
    resultCont.push(result[k]);
  } else if (k % 1 === 0) {
    resultCode.push(result[k]);
  }
}
let arr = [];
let arr2 = [];
let arr3 = [];

for (k in countrys) {
  for (j in resultCont) {
    if (countrys[k] === resultCont[j]) {
      arr.push(parseInt(j));
      arr2.push(parseInt(k));
    }
  }
}
for (i in arr) {
  arr3.push(resultCode[arr[i]]);
}

console.log(arr.length)
console.log(arr2.length)
console.log(arr3.length)

// console.dir(arr, { maxArrayLength: null });
// console.dir(arr3, { maxArrayLength: null });
// console.log(arr3.length);
// console.log(countrys.length)
// console.log(codesCont.length)
let total = []
for(i=0; i < countrys.length; i++){
  total.push({
    country: countrys[i],
    code: arr3[i]
  })
}
console.dir(total, {'maxArrayLength': null})
